default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vendelo_development
  username: postgres
  password: password

test:
  <<: *default
  database: vendelo_test
  username: postgres
  password: password

production:
  <<: *default
  username: vendelo_felipe
  password: <%= ENV["password"] %>